### ISSUE TITLE
sample data

### ISSUE THREAD

**Issue by gireeshkbogu** [andymcdgeo/las_explorer#8]
Hi, thank you for the package. Is there any sample data I can upload to this?

**Comment by dcslagel** [comment]
Here are a few resources for LAS files that could be used with Las Explorer:

The Equinor's Volve dataset:
 https://www.equinor.com/en/what-we-do/norwegian-continental-shelf-platforms/volve.html

Lasio's test LAS files:
https://github.com/kinverarity1/lasio/tree/master/tests/examples

Wellio.js's test LAS files:
https://github.com/JustinGOSSES/wellio.js/tree/master/assets
